### PR TITLE
Replace deprecated types

### PR DESCRIPTION
**Pull request by lymanepp**

### CODE REVIEW

**Comment by lymanepp** [comment]
https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases/

**Comment by twrecked** [comment]
Thanks for doing this. I've recently done the same exercise on hass-aarlo and completely forgot to do it here...

**Comment by lymanepp** [comment]
Thanks for merging. This is a useful component for testing several of my custom integrations. Thanks for sharing it.

**Comment by twrecked** [comment]
No problems.

And that's exactly how I use this component as well, make sure my appdaemon stuff works before I put it on my real system.

**Pull request merged**
